#!/usr/bin/env groovy

def gv

pipeline {
    agent any
    tools {
        maven 'maven-3.8'
    }
    parameters {
        choice(name: 'VERSION', choices: ['1.1.0', '1.2.0', '1.3.0'], description: '')
        booleanParam(name: 'executeTests', defaultValue: true, description: '')
    }
    stages {
        stage("init") {
            steps {
                script {
                   gv = load "Jenkinsfile-syntax/script.groovy"
                }
            }
        }
        stage("version increment") {
            steps {
                script {
                    gv.versionInc()
                }
            }
        }
        stage("buildJar") {
            steps {
                script {
                    gv.buildJar()
                }
            }
        }
        stage("buildImage") {
            when {
                expression {
                    params.executeTests
                    BRANCH_NAME == 'main'
                }
            }
            steps {
                script {
                    gv.buildImage()
                }
            }
        }
        stage("deployApp") {
            steps {
                script {
                    // env.ENV = input message: "Select the environment to deploy to", ok: "Done", parameters: [choice(name: 'ONE', choices: ['dev', 'staging', 'prod'], description: '')]

                    gv.deployApp()
                    // echo "Deploying to ${ENV}"
                    echo "Deploying to production"
                }
            } 
        }
        stage("commit version upate") {
            steps {
                script {
                    gv.versionUptCmmt()
                }
            }
        }
    }
}

